-- ============================================================
-- SIKUR / PantauKBM - Fondasi Monitoring KBM
-- TA 2026/2027
-- Jalankan di project Supabase: SIKUR-SMANSAKA
-- ============================================================

create table if not exists public.sikur_monitoring_kbm (
    id bigint generated by default as identity primary key,
    tanggal date not null,
    kelas text not null references public.sikur_kelas(kelas) on update cascade,
    jadwal_id bigint not null references public.sikur_jadwal(id) on update cascade,
    jam_ke integer not null,
    kode_guru text not null references public.sikur_guru(kode_guru) on update cascade,
    status_laporan text not null check (status_laporan in (
        'Hadir',
        'Terlambat',
        'Belum Hadir',
        'Meninggalkan Kelas Sebelum Selesai',
        'Tidak Hadir',
        'Guru Pengganti',
        'Tugas Mandiri'
    )),
    jam_masuk time,
    jam_keluar time,
    keterangan text,
    pelapor_nama text,
    pelapor_peran text not null default 'Ketua Kelas',
    status_verifikasi text not null default 'Perlu Verifikasi' check (status_verifikasi in (
        'Perlu Verifikasi',
        'Normal',
        'Tugas Kedinasan',
        'Izin',
        'Sakit',
        'Sudah Ditindaklanjuti'
    )),
    catatan_verifikasi text,
    diverifikasi_oleh uuid references auth.users(id),
    diverifikasi_pada timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tanggal, kelas, jadwal_id)
);

create index if not exists idx_sikur_monitoring_kbm_tanggal
    on public.sikur_monitoring_kbm(tanggal);

create index if not exists idx_sikur_monitoring_kbm_guru
    on public.sikur_monitoring_kbm(kode_guru);

create index if not exists idx_sikur_monitoring_kbm_kelas
    on public.sikur_monitoring_kbm(kelas);

create index if not exists idx_sikur_monitoring_kbm_verifikasi
    on public.sikur_monitoring_kbm(status_verifikasi);

alter table public.sikur_monitoring_kbm enable row level security;

-- Semua pengguna terautentikasi boleh membaca laporan.
drop policy if exists "monitoring_kbm_read_authenticated" on public.sikur_monitoring_kbm;
create policy "monitoring_kbm_read_authenticated"
on public.sikur_monitoring_kbm
for select
to authenticated
using (true);

-- Admin/Waka dapat mengelola dan memverifikasi seluruh laporan.
drop policy if exists "monitoring_kbm_manage_admin_waka" on public.sikur_monitoring_kbm;
create policy "monitoring_kbm_manage_admin_waka"
on public.sikur_monitoring_kbm
for all
to authenticated
using (
    exists (
        select 1 from public.sikur_profiles p
        where p.id = auth.uid()
          and p.role in ('admin','waka')
    )
)
with check (
    exists (
        select 1 from public.sikur_profiles p
        where p.id = auth.uid()
          and p.role in ('admin','waka')
    )
);

-- Catatan:
-- Hak INSERT ketua kelas sengaja BELUM dibuka untuk publik.
-- Tahap berikutnya menggunakan akun/identitas ketua kelas agar laporan
-- tidak dapat dikirim anonim dan tidak dapat mengatasnamakan kelas lain.
