-- ============================================================
-- SIKUR / PantauKBM - Akses Ketua Kelas
-- TA 2026/2027
-- Jalankan SETELAH SIKUR_04_MONITORING_KBM.sql
-- ============================================================

create table if not exists public.sikur_ketua_kelas (
    id bigint generated by default as identity primary key,
    tahun_ajaran text not null default '2026/2027',
    kelas text not null references public.sikur_kelas(kelas) on update cascade,
    nama_ketua text not null,
    pin_hash text not null,
    aktif boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tahun_ajaran, kelas)
);

alter table public.sikur_ketua_kelas enable row level security;

-- Daftar identitas ketua kelas hanya dapat dikelola Admin/Waka.
drop policy if exists "ketua_kelas_manage_admin_waka" on public.sikur_ketua_kelas;
create policy "ketua_kelas_manage_admin_waka"
on public.sikur_ketua_kelas
for all
to authenticated
using (
  exists (
    select 1 from public.sikur_profiles p
    where p.id = auth.uid() and p.role in ('admin','waka')
  )
)
with check (
  exists (
    select 1 from public.sikur_profiles p
    where p.id = auth.uid() and p.role in ('admin','waka')
  )
);

-- Fungsi login PantauKBM.
-- PIN tidak pernah dikirim kembali ke browser dan disimpan sebagai hash pgcrypto.
create extension if not exists pgcrypto;

create or replace function public.sikur_login_ketua_kelas(
    p_kelas text,
    p_pin text
)
returns table(kelas text, nama_ketua text, token text)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_row public.sikur_ketua_kelas%rowtype;
    v_token text;
begin
    select * into v_row
    from public.sikur_ketua_kelas k
    where k.tahun_ajaran='2026/2027'
      and k.kelas=p_kelas
      and k.aktif=true
      and k.pin_hash=crypt(p_pin,k.pin_hash);

    if not found then return; end if;

    v_token := encode(gen_random_bytes(24),'hex');

    insert into public.sikur_ketua_kelas_sesi(token_hash, ketua_id, berlaku_sampai)
    values (crypt(v_token,gen_salt('bf')),v_row.id,now()+interval '12 hours');

    return query select v_row.kelas,v_row.nama_ketua,v_token;
end;
$$;

create table if not exists public.sikur_ketua_kelas_sesi (
    id bigint generated by default as identity primary key,
    token_hash text not null,
    ketua_id bigint not null references public.sikur_ketua_kelas(id) on delete cascade,
    berlaku_sampai timestamptz not null,
    created_at timestamptz not null default now()
);

alter table public.sikur_ketua_kelas_sesi enable row level security;

-- RPC khusus untuk laporan ketua kelas. Browser siswa tidak mendapat INSERT langsung.
create or replace function public.sikur_lapor_kbm(
    p_token text,
    p_jadwal_id bigint,
    p_status text,
    p_jam_masuk time default null,
    p_jam_keluar time default null,
    p_keterangan text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_ketua public.sikur_ketua_kelas%rowtype;
    v_jadwal public.sikur_jadwal%rowtype;
    v_id bigint;
    v_hari text;
begin
    select k.* into v_ketua
    from public.sikur_ketua_kelas_sesi s
    join public.sikur_ketua_kelas k on k.id=s.ketua_id
    where s.berlaku_sampai>now()
      and crypt(p_token,s.token_hash)=s.token_hash
      and k.aktif=true
    order by s.id desc limit 1;

    if not found then raise exception 'Sesi PantauKBM tidak valid atau sudah berakhir'; end if;

    select * into v_jadwal from public.sikur_jadwal where id=p_jadwal_id;
    if not found then raise exception 'Jadwal tidak ditemukan'; end if;
    if v_jadwal.kelas<>v_ketua.kelas then raise exception 'Jadwal bukan milik kelas pelapor'; end if;

    v_hari := case extract(isodow from current_date)
      when 1 then 'Senin' when 2 then 'Selasa' when 3 then 'Rabu'
      when 4 then 'Kamis' when 5 then 'Jumat' when 6 then 'Sabtu' else 'Minggu' end;
    if v_jadwal.hari<>v_hari then raise exception 'Laporan hanya dapat dibuat untuk jadwal hari ini'; end if;

    if p_status not in ('Hadir','Terlambat','Belum Hadir','Meninggalkan Kelas Sebelum Selesai','Tidak Hadir','Guru Pengganti','Tugas Mandiri')
      then raise exception 'Status laporan tidak valid'; end if;

    insert into public.sikur_monitoring_kbm
      (tanggal,kelas,jadwal_id,jam_ke,kode_guru,status_laporan,jam_masuk,jam_keluar,keterangan,pelapor_nama,pelapor_peran,status_verifikasi)
    values
      (current_date,v_jadwal.kelas,v_jadwal.id,v_jadwal.jam_ke,v_jadwal.kode_guru,p_status,p_jam_masuk,p_jam_keluar,left(nullif(trim(p_keterangan),''),500),v_ketua.nama_ketua,'Ketua Kelas','Perlu Verifikasi')
    on conflict (tanggal,kelas,jadwal_id)
    do update set
      status_laporan=excluded.status_laporan,
      jam_masuk=excluded.jam_masuk,
      jam_keluar=excluded.jam_keluar,
      keterangan=excluded.keterangan,
      pelapor_nama=excluded.pelapor_nama,
      status_verifikasi='Perlu Verifikasi',
      catatan_verifikasi=null,
      diverifikasi_oleh=null,
      diverifikasi_pada=null,
      updated_at=now()
    returning id into v_id;

    return v_id;
end;
$$;

-- Admin/Waka membuat/mengganti PIN melalui fungsi ini.
create or replace function public.sikur_set_ketua_kelas(
    p_kelas text,
    p_nama text,
    p_pin text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (
      select 1 from public.sikur_profiles p
      where p.id=auth.uid() and p.role in ('admin','waka')
    ) then raise exception 'Akses ditolak'; end if;

    if length(trim(p_nama))<2 then raise exception 'Nama ketua kelas tidak valid'; end if;
    if p_pin !~ '^[0-9]{6}$' then raise exception 'PIN harus 6 angka'; end if;

    insert into public.sikur_ketua_kelas(tahun_ajaran,kelas,nama_ketua,pin_hash,aktif)
    values ('2026/2027',p_kelas,trim(p_nama),crypt(p_pin,gen_salt('bf')),true)
    on conflict (tahun_ajaran,kelas)
    do update set nama_ketua=excluded.nama_ketua,pin_hash=excluded.pin_hash,aktif=true,updated_at=now();
end;
$$;

grant execute on function public.sikur_login_ketua_kelas(text,text) to anon, authenticated;
grant execute on function public.sikur_lapor_kbm(text,bigint,text,time,time,text) to anon, authenticated;
grant execute on function public.sikur_set_ketua_kelas(text,text,text) to authenticated;

-- Tidak ada INSERT/UPDATE/DELETE langsung untuk anon pada tabel monitoring.
-- Laporan siswa hanya melalui RPC yang memvalidasi kelas dan jadwal.
